/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecuredocRouteImport } from './routes/securedoc'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as IndexRouteImport } from './routes/index'

const SecuredocRoute = SecuredocRouteImport.update({
  id: '/securedoc',
  path: '/securedoc',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/securedoc': typeof SecuredocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/securedoc': typeof SecuredocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/securedoc': typeof SecuredocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deploy' | '/securedoc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deploy' | '/securedoc'
  id: '__root__' | '/' | '/deploy' | '/securedoc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeployRoute: typeof DeployRoute
  SecuredocRoute: typeof SecuredocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/securedoc': {
      id: '/securedoc'
      path: '/securedoc'
      fullPath: '/securedoc'
      preLoaderRoute: typeof SecuredocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeployRoute: DeployRoute,
  SecuredocRoute: SecuredocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
